- hosts: localhost
  become: true
  tasks:
  - name : Updating repo
    apt: update_cache=yes
    register: repo

  - name: Install htop
    apt: 
        name: htop 
        state: present
        update_cache: yes
  - name : Displaying updated content
    debug:
      var: repo

